//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MVCFormsFormModel", "FK_FormFields_FormFieldTypes", "FormFieldTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcFormsV2.Models.FormFieldType), "FormFields", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFormsV2.Models.FormField), true)]
[assembly: EdmRelationshipAttribute("MVCFormsFormModel", "FK_FormFields_Forms", "Forms", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcFormsV2.Models.Form), "FormFields", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFormsV2.Models.FormField), true)]

#endregion

namespace MvcFormsV2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MVCFormsFormEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MVCFormsFormEntities object using the connection string found in the 'MVCFormsFormEntities' section of the application configuration file.
        /// </summary>
        public MVCFormsFormEntities() : base("name=MVCFormsFormEntities", "MVCFormsFormEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCFormsFormEntities object.
        /// </summary>
        public MVCFormsFormEntities(string connectionString) : base(connectionString, "MVCFormsFormEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCFormsFormEntities object.
        /// </summary>
        public MVCFormsFormEntities(EntityConnection connection) : base(connection, "MVCFormsFormEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormField> FormFields
        {
            get
            {
                if ((_FormFields == null))
                {
                    _FormFields = base.CreateObjectSet<FormField>("FormFields");
                }
                return _FormFields;
            }
        }
        private ObjectSet<FormField> _FormFields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormFieldType> FormFieldTypes
        {
            get
            {
                if ((_FormFieldTypes == null))
                {
                    _FormFieldTypes = base.CreateObjectSet<FormFieldType>("FormFieldTypes");
                }
                return _FormFieldTypes;
            }
        }
        private ObjectSet<FormFieldType> _FormFieldTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Form> Forms
        {
            get
            {
                if ((_Forms == null))
                {
                    _Forms = base.CreateObjectSet<Form>("Forms");
                }
                return _Forms;
            }
        }
        private ObjectSet<Form> _Forms;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormFields(FormField formField)
        {
            base.AddObject("FormFields", formField);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormFieldTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormFieldTypes(FormFieldType formFieldType)
        {
            base.AddObject("FormFieldTypes", formFieldType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForms(Form form)
        {
            base.AddObject("Forms", form);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCFormsFormModel", Name="Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Form object.
        /// </summary>
        /// <param name="uid">Initial value of the Uid property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static Form CreateForm(global::System.Guid uid, global::System.Guid userId, global::System.DateTime timestamp)
        {
            Form form = new Form();
            form.Uid = uid;
            form.UserId = userId;
            form.Timestamp = timestamp;
            return form;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                if (_Uid != value)
                {
                    OnUidChanging(value);
                    ReportPropertyChanging("Uid");
                    _Uid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Uid");
                    OnUidChanged();
                }
            }
        }
        private global::System.Guid _Uid;
        partial void OnUidChanging(global::System.Guid value);
        partial void OnUidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortPath
        {
            get
            {
                return _ShortPath;
            }
            set
            {
                OnShortPathChanging(value);
                ReportPropertyChanging("ShortPath");
                _ShortPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortPath");
                OnShortPathChanged();
            }
        }
        private global::System.String _ShortPath;
        partial void OnShortPathChanging(global::System.String value);
        partial void OnShortPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormName
        {
            get
            {
                return _FormName;
            }
            set
            {
                OnFormNameChanging(value);
                ReportPropertyChanging("FormName");
                _FormName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormName");
                OnFormNameChanged();
            }
        }
        private global::System.String _FormName;
        partial void OnFormNameChanging(global::System.String value);
        partial void OnFormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCFormsFormModel", "FK_FormFields_Forms", "FormFields")]
        public EntityCollection<FormField> FormFields
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormField>("MVCFormsFormModel.FK_FormFields_Forms", "FormFields");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormField>("MVCFormsFormModel.FK_FormFields_Forms", "FormFields", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCFormsFormModel", Name="FormField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormField : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormField object.
        /// </summary>
        /// <param name="uid">Initial value of the Uid property.</param>
        /// <param name="formUid">Initial value of the FormUid property.</param>
        /// <param name="formFieldTypeUid">Initial value of the FormFieldTypeUid property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static FormField CreateFormField(global::System.Guid uid, global::System.Guid formUid, global::System.Guid formFieldTypeUid, global::System.Int32 sortOrder, global::System.DateTime timestamp)
        {
            FormField formField = new FormField();
            formField.Uid = uid;
            formField.FormUid = formUid;
            formField.FormFieldTypeUid = formFieldTypeUid;
            formField.SortOrder = sortOrder;
            formField.Timestamp = timestamp;
            return formField;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                if (_Uid != value)
                {
                    OnUidChanging(value);
                    ReportPropertyChanging("Uid");
                    _Uid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Uid");
                    OnUidChanged();
                }
            }
        }
        private global::System.Guid _Uid;
        partial void OnUidChanging(global::System.Guid value);
        partial void OnUidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FormUid
        {
            get
            {
                return _FormUid;
            }
            set
            {
                OnFormUidChanging(value);
                ReportPropertyChanging("FormUid");
                _FormUid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormUid");
                OnFormUidChanged();
            }
        }
        private global::System.Guid _FormUid;
        partial void OnFormUidChanging(global::System.Guid value);
        partial void OnFormUidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FormFieldTypeUid
        {
            get
            {
                return _FormFieldTypeUid;
            }
            set
            {
                OnFormFieldTypeUidChanging(value);
                ReportPropertyChanging("FormFieldTypeUid");
                _FormFieldTypeUid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormFieldTypeUid");
                OnFormFieldTypeUidChanged();
            }
        }
        private global::System.Guid _FormFieldTypeUid;
        partial void OnFormFieldTypeUidChanging(global::System.Guid value);
        partial void OnFormFieldTypeUidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormFieldName
        {
            get
            {
                return _FormFieldName;
            }
            set
            {
                OnFormFieldNameChanging(value);
                ReportPropertyChanging("FormFieldName");
                _FormFieldName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormFieldName");
                OnFormFieldNameChanged();
            }
        }
        private global::System.String _FormFieldName;
        partial void OnFormFieldNameChanging(global::System.String value);
        partial void OnFormFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormFieldPrompt
        {
            get
            {
                return _FormFieldPrompt;
            }
            set
            {
                OnFormFieldPromptChanging(value);
                ReportPropertyChanging("FormFieldPrompt");
                _FormFieldPrompt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormFieldPrompt");
                OnFormFieldPromptChanged();
            }
        }
        private global::System.String _FormFieldPrompt;
        partial void OnFormFieldPromptChanging(global::System.String value);
        partial void OnFormFieldPromptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LiteralText
        {
            get
            {
                return _LiteralText;
            }
            set
            {
                OnLiteralTextChanging(value);
                ReportPropertyChanging("LiteralText");
                _LiteralText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LiteralText");
                OnLiteralTextChanged();
            }
        }
        private global::System.String _LiteralText;
        partial void OnLiteralTextChanging(global::System.String value);
        partial void OnLiteralTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsRequired
        {
            get
            {
                return _IsRequired;
            }
            set
            {
                OnIsRequiredChanging(value);
                ReportPropertyChanging("IsRequired");
                _IsRequired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRequired");
                OnIsRequiredChanged();
            }
        }
        private Nullable<global::System.Byte> _IsRequired;
        partial void OnIsRequiredChanging(Nullable<global::System.Byte> value);
        partial void OnIsRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsHidden
        {
            get
            {
                return _IsHidden;
            }
            set
            {
                OnIsHiddenChanging(value);
                ReportPropertyChanging("IsHidden");
                _IsHidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsHidden");
                OnIsHiddenChanged();
            }
        }
        private Nullable<global::System.Byte> _IsHidden;
        partial void OnIsHiddenChanging(Nullable<global::System.Byte> value);
        partial void OnIsHiddenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsMultipleSelect
        {
            get
            {
                return _IsMultipleSelect;
            }
            set
            {
                OnIsMultipleSelectChanging(value);
                ReportPropertyChanging("IsMultipleSelect");
                _IsMultipleSelect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMultipleSelect");
                OnIsMultipleSelectChanged();
            }
        }
        private Nullable<global::System.Byte> _IsMultipleSelect;
        partial void OnIsMultipleSelectChanging(Nullable<global::System.Byte> value);
        partial void OnIsMultipleSelectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsEmptyOption
        {
            get
            {
                return _IsEmptyOption;
            }
            set
            {
                OnIsEmptyOptionChanging(value);
                ReportPropertyChanging("IsEmptyOption");
                _IsEmptyOption = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEmptyOption");
                OnIsEmptyOptionChanged();
            }
        }
        private Nullable<global::System.Byte> _IsEmptyOption;
        partial void OnIsEmptyOptionChanging(Nullable<global::System.Byte> value);
        partial void OnIsEmptyOptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmptyOption
        {
            get
            {
                return _EmptyOption;
            }
            set
            {
                OnEmptyOptionChanging(value);
                ReportPropertyChanging("EmptyOption");
                _EmptyOption = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmptyOption");
                OnEmptyOptionChanged();
            }
        }
        private global::System.String _EmptyOption;
        partial void OnEmptyOptionChanging(global::System.String value);
        partial void OnEmptyOptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Options
        {
            get
            {
                return _Options;
            }
            set
            {
                OnOptionsChanging(value);
                ReportPropertyChanging("Options");
                _Options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Options");
                OnOptionsChanged();
            }
        }
        private global::System.String _Options;
        partial void OnOptionsChanging(global::System.String value);
        partial void OnOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidExtensions
        {
            get
            {
                return _ValidExtensions;
            }
            set
            {
                OnValidExtensionsChanging(value);
                ReportPropertyChanging("ValidExtensions");
                _ValidExtensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidExtensions");
                OnValidExtensionsChanged();
            }
        }
        private global::System.String _ValidExtensions;
        partial void OnValidExtensionsChanging(global::System.String value);
        partial void OnValidExtensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorExtensions
        {
            get
            {
                return _ErrorExtensions;
            }
            set
            {
                OnErrorExtensionsChanging(value);
                ReportPropertyChanging("ErrorExtensions");
                _ErrorExtensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorExtensions");
                OnErrorExtensionsChanged();
            }
        }
        private global::System.String _ErrorExtensions;
        partial void OnErrorExtensionsChanging(global::System.String value);
        partial void OnErrorExtensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Orientation
        {
            get
            {
                return _Orientation;
            }
            set
            {
                OnOrientationChanging(value);
                ReportPropertyChanging("Orientation");
                _Orientation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Orientation");
                OnOrientationChanged();
            }
        }
        private global::System.String _Orientation;
        partial void OnOrientationChanging(global::System.String value);
        partial void OnOrientationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ListSize
        {
            get
            {
                return _ListSize;
            }
            set
            {
                OnListSizeChanging(value);
                ReportPropertyChanging("ListSize");
                _ListSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListSize");
                OnListSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _ListSize;
        partial void OnListSizeChanging(Nullable<global::System.Int32> value);
        partial void OnListSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rows
        {
            get
            {
                return _Rows;
            }
            set
            {
                OnRowsChanging(value);
                ReportPropertyChanging("Rows");
                _Rows = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rows");
                OnRowsChanged();
            }
        }
        private Nullable<global::System.Int32> _Rows;
        partial void OnRowsChanging(Nullable<global::System.Int32> value);
        partial void OnRowsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cols
        {
            get
            {
                return _Cols;
            }
            set
            {
                OnColsChanging(value);
                ReportPropertyChanging("Cols");
                _Cols = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cols");
                OnColsChanged();
            }
        }
        private Nullable<global::System.Int32> _Cols;
        partial void OnColsChanging(Nullable<global::System.Int32> value);
        partial void OnColsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxSizeBytes
        {
            get
            {
                return _MaxSizeBytes;
            }
            set
            {
                OnMaxSizeBytesChanging(value);
                ReportPropertyChanging("MaxSizeBytes");
                _MaxSizeBytes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxSizeBytes");
                OnMaxSizeBytesChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxSizeBytes;
        partial void OnMaxSizeBytesChanging(Nullable<global::System.Int32> value);
        partial void OnMaxSizeBytesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCFormsFormModel", "FK_FormFields_FormFieldTypes", "FormFieldTypes")]
        public FormFieldType FormFieldType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormFieldType>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFieldTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormFieldType>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFieldTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FormFieldType> FormFieldTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormFieldType>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFieldTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FormFieldType>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFieldTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCFormsFormModel", "FK_FormFields_Forms", "Forms")]
        public Form Form
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("MVCFormsFormModel.FK_FormFields_Forms", "Forms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("MVCFormsFormModel.FK_FormFields_Forms", "Forms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Form> FormReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("MVCFormsFormModel.FK_FormFields_Forms", "Forms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Form>("MVCFormsFormModel.FK_FormFields_Forms", "Forms", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCFormsFormModel", Name="FormFieldType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormFieldType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormFieldType object.
        /// </summary>
        /// <param name="uid">Initial value of the Uid property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static FormFieldType CreateFormFieldType(global::System.Guid uid, global::System.DateTime timestamp)
        {
            FormFieldType formFieldType = new FormFieldType();
            formFieldType.Uid = uid;
            formFieldType.Timestamp = timestamp;
            return formFieldType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                if (_Uid != value)
                {
                    OnUidChanging(value);
                    ReportPropertyChanging("Uid");
                    _Uid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Uid");
                    OnUidChanged();
                }
            }
        }
        private global::System.Guid _Uid;
        partial void OnUidChanging(global::System.Guid value);
        partial void OnUidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldTypeName
        {
            get
            {
                return _FieldTypeName;
            }
            set
            {
                OnFieldTypeNameChanging(value);
                ReportPropertyChanging("FieldTypeName");
                _FieldTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FieldTypeName");
                OnFieldTypeNameChanged();
            }
        }
        private global::System.String _FieldTypeName;
        partial void OnFieldTypeNameChanging(global::System.String value);
        partial void OnFieldTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldType
        {
            get
            {
                return _FieldType;
            }
            set
            {
                OnFieldTypeChanging(value);
                ReportPropertyChanging("FieldType");
                _FieldType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FieldType");
                OnFieldTypeChanged();
            }
        }
        private global::System.String _FieldType;
        partial void OnFieldTypeChanging(global::System.String value);
        partial void OnFieldTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ControlType
        {
            get
            {
                return _ControlType;
            }
            set
            {
                OnControlTypeChanging(value);
                ReportPropertyChanging("ControlType");
                _ControlType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ControlType");
                OnControlTypeChanged();
            }
        }
        private global::System.String _ControlType;
        partial void OnControlTypeChanging(global::System.String value);
        partial void OnControlTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorMsgRequired
        {
            get
            {
                return _ErrorMsgRequired;
            }
            set
            {
                OnErrorMsgRequiredChanging(value);
                ReportPropertyChanging("ErrorMsgRequired");
                _ErrorMsgRequired = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorMsgRequired");
                OnErrorMsgRequiredChanged();
            }
        }
        private global::System.String _ErrorMsgRequired;
        partial void OnErrorMsgRequiredChanging(global::System.String value);
        partial void OnErrorMsgRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegExDefault
        {
            get
            {
                return _RegExDefault;
            }
            set
            {
                OnRegExDefaultChanging(value);
                ReportPropertyChanging("RegExDefault");
                _RegExDefault = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegExDefault");
                OnRegExDefaultChanged();
            }
        }
        private global::System.String _RegExDefault;
        partial void OnRegExDefaultChanging(global::System.String value);
        partial void OnRegExDefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorMsgRegEx
        {
            get
            {
                return _ErrorMsgRegEx;
            }
            set
            {
                OnErrorMsgRegExChanging(value);
                ReportPropertyChanging("ErrorMsgRegEx");
                _ErrorMsgRegEx = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorMsgRegEx");
                OnErrorMsgRegExChanged();
            }
        }
        private global::System.String _ErrorMsgRegEx;
        partial void OnErrorMsgRegExChanging(global::System.String value);
        partial void OnErrorMsgRegExChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidExtensions
        {
            get
            {
                return _ValidExtensions;
            }
            set
            {
                OnValidExtensionsChanging(value);
                ReportPropertyChanging("ValidExtensions");
                _ValidExtensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidExtensions");
                OnValidExtensionsChanged();
            }
        }
        private global::System.String _ValidExtensions;
        partial void OnValidExtensionsChanging(global::System.String value);
        partial void OnValidExtensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorExtensions
        {
            get
            {
                return _ErrorExtensions;
            }
            set
            {
                OnErrorExtensionsChanging(value);
                ReportPropertyChanging("ErrorExtensions");
                _ErrorExtensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorExtensions");
                OnErrorExtensionsChanged();
            }
        }
        private global::System.String _ErrorExtensions;
        partial void OnErrorExtensionsChanging(global::System.String value);
        partial void OnErrorExtensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCFormsFormModel", "FK_FormFields_FormFieldTypes", "FormFields")]
        public EntityCollection<FormField> FormFields
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormField>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFields");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormField>("MVCFormsFormModel.FK_FormFields_FormFieldTypes", "FormFields", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
